### ISSUE TITLE
2nd Capstone project review

### ISSUE THREAD

**Issue by MattGomb** [MattGomb/module2-capstone#61]
https://github.com/users/MattGomb/projects/2

There's two of us for this project: @Oklukeok , and myself

**Comment by Reem-lab** [comment]
# Hi Team, 👋🏻👋🏻 

Good job so far! 🔥😊🙏🏻🚀💯💪🏻
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Great job on set up the kanban 💪🏻

## Required Changes ♻️
_Check the comments under the review._
- [x] I think you forget to add information in your issue to tell who is working on this project so kindly according to the requirements kindly add it in your issue. 💪🏻💯
![image](https://user-images.githubusercontent.com/58553711/197649846-af6579e3-1a31-4032-abe7-c70769f7e54f.png)

- [x] I think you forget to assign the tasks to each member so please assign it between you and your partner in your kanban board 
![image](https://user-images.githubusercontent.com/58553711/197649971-0ce28738-3ab6-43c2-9ad9-5043975a4a9d.png)

 You can do it through the issues just press on assigners and select the student 💯💪🏻🚀🙏🏻
![image](https://user-images.githubusercontent.com/58553711/197650108-a16b1dad-83c2-4a5a-92bb-add77fe7ec9e.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MattGomb** [comment]
Hi! 

Thanks for the comments, you are completely right, i forgot to add these things, i was in a hurry to join a call..! :) 

All issues are now fixed!

**Comment by Santiago220991** [comment]
Hi @Reem-lab @Oklukeok,
I'm Santiago your reviewer for this PR. :wave: :wave:  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/fDbzXb6Cv5L56/giphy.gif"/>

## Highlights
:heavy_check_mark: Applied changes suggested by the last code reviewer.
:heavy_check_mark: Good kanban board.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
